# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.robot = QtWidgets.QWidget(self.centralwidget)
        self.robot.setGeometry(QtCore.QRect(-1, -1, 841, 691))
        self.robot.setStyleSheet("#robot{\n"
"background-image: url(:/Robot_Background.jpg);\n"
"}")
        self.robot.setObjectName("robot")
        self.m_05_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_05_spinbox.setGeometry(QtCore.QRect(60, 60, 71, 30))
        self.m_05_spinbox.setMaximum(300.0)
        self.m_05_spinbox.setSingleStep(0.293)
        self.m_05_spinbox.setObjectName("m_05_spinbox")
        self.m_03_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_03_spinbox.setGeometry(QtCore.QRect(170, 60, 71, 30))
        self.m_03_spinbox.setMaximum(300.0)
        self.m_03_spinbox.setSingleStep(0.293)
        self.m_03_spinbox.setObjectName("m_03_spinbox")
        self.m_01_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_01_spinbox.setGeometry(QtCore.QRect(280, 60, 71, 30))
        self.m_01_spinbox.setMaximum(300.0)
        self.m_01_spinbox.setSingleStep(0.293)
        self.m_01_spinbox.setObjectName("m_01_spinbox")
        self.m_02_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_02_spinbox.setGeometry(QtCore.QRect(490, 60, 71, 30))
        self.m_02_spinbox.setMaximum(300.0)
        self.m_02_spinbox.setSingleStep(0.293)
        self.m_02_spinbox.setObjectName("m_02_spinbox")
        self.m_04_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_04_spinbox.setGeometry(QtCore.QRect(590, 60, 71, 30))
        self.m_04_spinbox.setMaximum(300.0)
        self.m_04_spinbox.setSingleStep(0.293)
        self.m_04_spinbox.setObjectName("m_04_spinbox")
        self.m_06_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_06_spinbox.setGeometry(QtCore.QRect(700, 60, 71, 30))
        self.m_06_spinbox.setMaximum(300.0)
        self.m_06_spinbox.setSingleStep(0.293)
        self.m_06_spinbox.setObjectName("m_06_spinbox")
        self.m_07_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_07_spinbox.setGeometry(QtCore.QRect(220, 230, 71, 30))
        self.m_07_spinbox.setMaximum(300.0)
        self.m_07_spinbox.setSingleStep(0.293)
        self.m_07_spinbox.setObjectName("m_07_spinbox")
        self.m_08_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_08_spinbox.setGeometry(QtCore.QRect(550, 230, 71, 30))
        self.m_08_spinbox.setMaximum(300.0)
        self.m_08_spinbox.setSingleStep(0.293)
        self.m_08_spinbox.setObjectName("m_08_spinbox")
        self.m_09_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_09_spinbox.setGeometry(QtCore.QRect(150, 360, 71, 30))
        self.m_09_spinbox.setMaximum(300.0)
        self.m_09_spinbox.setSingleStep(0.293)
        self.m_09_spinbox.setObjectName("m_09_spinbox")
        self.m_10_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_10_spinbox.setGeometry(QtCore.QRect(610, 350, 71, 30))
        self.m_10_spinbox.setMaximum(300.0)
        self.m_10_spinbox.setSingleStep(0.293)
        self.m_10_spinbox.setObjectName("m_10_spinbox")
        self.m_11_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_11_spinbox.setGeometry(QtCore.QRect(180, 290, 71, 30))
        self.m_11_spinbox.setMaximum(300.0)
        self.m_11_spinbox.setSingleStep(0.293)
        self.m_11_spinbox.setObjectName("m_11_spinbox")
        self.m_12_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_12_spinbox.setGeometry(QtCore.QRect(590, 290, 71, 30))
        self.m_12_spinbox.setMaximum(300.0)
        self.m_12_spinbox.setSingleStep(0.293)
        self.m_12_spinbox.setObjectName("m_12_spinbox")
        self.m_13_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_13_spinbox.setGeometry(QtCore.QRect(190, 430, 71, 30))
        self.m_13_spinbox.setMaximum(300.0)
        self.m_13_spinbox.setSingleStep(0.293)
        self.m_13_spinbox.setObjectName("m_13_spinbox")
        self.m_14_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_14_spinbox.setGeometry(QtCore.QRect(580, 430, 71, 30))
        self.m_14_spinbox.setMaximum(300.0)
        self.m_14_spinbox.setSingleStep(0.293)
        self.m_14_spinbox.setObjectName("m_14_spinbox")
        self.m_15_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_15_spinbox.setGeometry(QtCore.QRect(180, 510, 71, 30))
        self.m_15_spinbox.setMaximum(300.0)
        self.m_15_spinbox.setSingleStep(0.293)
        self.m_15_spinbox.setObjectName("m_15_spinbox")
        self.m_16_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_16_spinbox.setGeometry(QtCore.QRect(580, 510, 71, 30))
        self.m_16_spinbox.setMaximum(300.0)
        self.m_16_spinbox.setSingleStep(0.293)
        self.m_16_spinbox.setObjectName("m_16_spinbox")
        self.m_17_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_17_spinbox.setGeometry(QtCore.QRect(130, 580, 71, 30))
        self.m_17_spinbox.setMaximum(300.0)
        self.m_17_spinbox.setSingleStep(0.293)
        self.m_17_spinbox.setObjectName("m_17_spinbox")
        self.m_18_spinbox = QtWidgets.QDoubleSpinBox(self.robot)
        self.m_18_spinbox.setGeometry(QtCore.QRect(640, 580, 71, 30))
        self.m_18_spinbox.setMaximum(300.0)
        self.m_18_spinbox.setSingleStep(0.293)
        self.m_18_spinbox.setObjectName("m_18_spinbox")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(850, 0, 271, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.motor = QtWidgets.QGroupBox(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motor.sizePolicy().hasHeightForWidth())
        self.motor.setSizePolicy(sizePolicy)
        self.motor.setMinimumSize(QtCore.QSize(250, 180))
        self.motor.setObjectName("motor")
        self.id = QtWidgets.QComboBox(self.motor)
        self.id.setGeometry(QtCore.QRect(100, 0, 90, 28))
        self.id.setBaseSize(QtCore.QSize(90, 0))
        self.id.setAutoFillBackground(True)
        self.id.setCurrentText("")
        self.id.setMaxVisibleItems(18)
        self.id.setMaxCount(18)
        self.id.setObjectName("id")
        self.torque = QtWidgets.QLabel(self.motor)
        self.torque.setGeometry(QtCore.QRect(10, 30, 66, 20))
        self.torque.setObjectName("torque")
        self.goal_position = QtWidgets.QLabel(self.motor)
        self.goal_position.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.goal_position.setObjectName("goal_position")
        self.position = QtWidgets.QLabel(self.motor)
        self.position.setGeometry(QtCore.QRect(10, 50, 66, 20))
        self.position.setObjectName("position")
        self.speed = QtWidgets.QLabel(self.motor)
        self.speed.setGeometry(QtCore.QRect(10, 90, 66, 20))
        self.speed.setObjectName("speed")
        self.goal_speed = QtWidgets.QLabel(self.motor)
        self.goal_speed.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.goal_speed.setObjectName("goal_speed")
        self.moving = QtWidgets.QLabel(self.motor)
        self.moving.setGeometry(QtCore.QRect(10, 130, 81, 20))
        self.moving.setObjectName("moving")
        self.temperature = QtWidgets.QLabel(self.motor)
        self.temperature.setGeometry(QtCore.QRect(10, 150, 91, 20))
        self.temperature.setObjectName("temperature")
        self.verticalLayout.addWidget(self.motor)
        self.imu = QtWidgets.QGroupBox(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imu.sizePolicy().hasHeightForWidth())
        self.imu.setSizePolicy(sizePolicy)
        self.imu.setMinimumSize(QtCore.QSize(250, 300))
        self.imu.setObjectName("imu")
        self.label_8 = QtWidgets.QLabel(self.imu)
        self.label_8.setGeometry(QtCore.QRect(0, 110, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.imu)
        self.label_9.setGeometry(QtCore.QRect(0, 190, 91, 20))
        self.label_9.setObjectName("label_9")
        self.speed_x = QtWidgets.QLabel(self.imu)
        self.speed_x.setGeometry(QtCore.QRect(20, 130, 41, 20))
        self.speed_x.setObjectName("speed_x")
        self.speed_y = QtWidgets.QLabel(self.imu)
        self.speed_y.setGeometry(QtCore.QRect(20, 150, 41, 20))
        self.speed_y.setObjectName("speed_y")
        self.speed_z = QtWidgets.QLabel(self.imu)
        self.speed_z.setGeometry(QtCore.QRect(20, 170, 41, 20))
        self.speed_z.setObjectName("speed_z")
        self.acceleration_x = QtWidgets.QLabel(self.imu)
        self.acceleration_x.setGeometry(QtCore.QRect(20, 210, 41, 20))
        self.acceleration_x.setObjectName("acceleration_x")
        self.acceleration_z = QtWidgets.QLabel(self.imu)
        self.acceleration_z.setGeometry(QtCore.QRect(20, 250, 41, 20))
        self.acceleration_z.setObjectName("acceleration_z")
        self.acceleration_y = QtWidgets.QLabel(self.imu)
        self.acceleration_y.setGeometry(QtCore.QRect(20, 230, 41, 20))
        self.acceleration_y.setObjectName("acceleration_y")
        self.position_z = QtWidgets.QLabel(self.imu)
        self.position_z.setGeometry(QtCore.QRect(20, 90, 41, 20))
        self.position_z.setObjectName("position_z")
        self.position_x = QtWidgets.QLabel(self.imu)
        self.position_x.setGeometry(QtCore.QRect(20, 50, 41, 20))
        self.position_x.setObjectName("position_x")
        self.label_18 = QtWidgets.QLabel(self.imu)
        self.label_18.setGeometry(QtCore.QRect(0, 30, 91, 20))
        self.label_18.setObjectName("label_18")
        self.position_y = QtWidgets.QLabel(self.imu)
        self.position_y.setGeometry(QtCore.QRect(20, 70, 41, 20))
        self.position_y.setObjectName("position_y")
        self.verticalLayout.addWidget(self.imu)
        self.battery = QtWidgets.QGroupBox(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battery.sizePolicy().hasHeightForWidth())
        self.battery.setSizePolicy(sizePolicy)
        self.battery.setMinimumSize(QtCore.QSize(250, 260))
        self.battery.setObjectName("battery")
        self.fw_ver_label = QtWidgets.QLabel(self.battery)
        self.fw_ver_label.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.fw_ver_label.setObjectName("fw_ver_label")
        self.active_label = QtWidgets.QLabel(self.battery)
        self.active_label.setGeometry(QtCore.QRect(10, 50, 71, 20))
        self.active_label.setObjectName("active_label")
        self.profile_label = QtWidgets.QLabel(self.battery)
        self.profile_label.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.profile_label.setObjectName("profile_label")
        self.good_label = QtWidgets.QLabel(self.battery)
        self.good_label.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.good_label.setObjectName("good_label")
        self.src_type_label = QtWidgets.QLabel(self.battery)
        self.src_type_label.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.src_type_label.setObjectName("src_type_label")
        self.levels_label = QtWidgets.QLabel(self.battery)
        self.levels_label.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.levels_label.setObjectName("levels_label")
        self.max_v_label = QtWidgets.QLabel(self.battery)
        self.max_v_label.setGeometry(QtCore.QRect(30, 150, 71, 20))
        self.max_v_label.setObjectName("max_v_label")
        self.good_v_label = QtWidgets.QLabel(self.battery)
        self.good_v_label.setGeometry(QtCore.QRect(30, 170, 71, 20))
        self.good_v_label.setObjectName("good_v_label")
        self.low_v_label = QtWidgets.QLabel(self.battery)
        self.low_v_label.setGeometry(QtCore.QRect(30, 190, 71, 20))
        self.low_v_label.setObjectName("low_v_label")
        self.critical_v_label = QtWidgets.QLabel(self.battery)
        self.critical_v_label.setGeometry(QtCore.QRect(30, 210, 71, 20))
        self.critical_v_label.setObjectName("critical_v_label")
        self.voltage_label = QtWidgets.QLabel(self.battery)
        self.voltage_label.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.voltage_label.setObjectName("voltage_label")
        self.voltage = QtWidgets.QLabel(self.battery)
        self.voltage.setGeometry(QtCore.QRect(120, 230, 131, 20))
        self.voltage.setText("")
        self.voltage.setObjectName("voltage")
        self.fw_ver = QtWidgets.QLabel(self.battery)
        self.fw_ver.setGeometry(QtCore.QRect(80, 30, 171, 20))
        self.fw_ver.setText("")
        self.fw_ver.setObjectName("fw_ver")
        self.critical_v = QtWidgets.QLabel(self.battery)
        self.critical_v.setGeometry(QtCore.QRect(120, 210, 131, 20))
        self.critical_v.setText("")
        self.critical_v.setObjectName("critical_v")
        self.low_v = QtWidgets.QLabel(self.battery)
        self.low_v.setGeometry(QtCore.QRect(120, 190, 131, 20))
        self.low_v.setText("")
        self.low_v.setObjectName("low_v")
        self.good_v = QtWidgets.QLabel(self.battery)
        self.good_v.setGeometry(QtCore.QRect(120, 170, 131, 20))
        self.good_v.setText("")
        self.good_v.setObjectName("good_v")
        self.max_v = QtWidgets.QLabel(self.battery)
        self.max_v.setGeometry(QtCore.QRect(120, 150, 131, 20))
        self.max_v.setText("")
        self.max_v.setObjectName("max_v")
        self.src_type = QtWidgets.QLabel(self.battery)
        self.src_type.setGeometry(QtCore.QRect(80, 110, 171, 20))
        self.src_type.setText("")
        self.src_type.setObjectName("src_type")
        self.good = QtWidgets.QLabel(self.battery)
        self.good.setGeometry(QtCore.QRect(80, 90, 171, 20))
        self.good.setText("")
        self.good.setObjectName("good")
        self.profile = QtWidgets.QLabel(self.battery)
        self.profile.setGeometry(QtCore.QRect(80, 70, 171, 20))
        self.profile.setText("")
        self.profile.setObjectName("profile")
        self.active = QtWidgets.QLabel(self.battery)
        self.active.setGeometry(QtCore.QRect(80, 50, 171, 20))
        self.active.setText("")
        self.active.setObjectName("active")
        self.verticalLayout.addWidget(self.battery)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.motor.setTitle(_translate("MainWindow", "Stato motore "))
        self.torque.setText(_translate("MainWindow", "Torque"))
        self.goal_position.setText(_translate("MainWindow", "Goal Position"))
        self.position.setText(_translate("MainWindow", "Position"))
        self.speed.setText(_translate("MainWindow", "Speed"))
        self.goal_speed.setText(_translate("MainWindow", "Goal Speed"))
        self.moving.setText(_translate("MainWindow", "Moving"))
        self.temperature.setText(_translate("MainWindow", "Temperature"))
        self.imu.setTitle(_translate("MainWindow", "Dati IMU"))
        self.label_8.setText(_translate("MainWindow", "Speed"))
        self.label_9.setText(_translate("MainWindow", "Acceleration"))
        self.speed_x.setText(_translate("MainWindow", "X:"))
        self.speed_y.setText(_translate("MainWindow", "Y:"))
        self.speed_z.setText(_translate("MainWindow", "Z:"))
        self.acceleration_x.setText(_translate("MainWindow", "X:"))
        self.acceleration_z.setText(_translate("MainWindow", "Z:"))
        self.acceleration_y.setText(_translate("MainWindow", "Y:"))
        self.position_z.setText(_translate("MainWindow", "Z:"))
        self.position_x.setText(_translate("MainWindow", "X:"))
        self.label_18.setText(_translate("MainWindow", "Position"))
        self.position_y.setText(_translate("MainWindow", "Y:"))
        self.battery.setTitle(_translate("MainWindow", "Stato batteria"))
        self.fw_ver_label.setText(_translate("MainWindow", "FW ver:"))
        self.active_label.setText(_translate("MainWindow", "Active:"))
        self.profile_label.setText(_translate("MainWindow", "Profile:"))
        self.good_label.setText(_translate("MainWindow", "Good:"))
        self.src_type_label.setText(_translate("MainWindow", "Src type:"))
        self.levels_label.setText(_translate("MainWindow", "Levels:"))
        self.max_v_label.setText(_translate("MainWindow", "Max:"))
        self.good_v_label.setText(_translate("MainWindow", "Good:"))
        self.low_v_label.setText(_translate("MainWindow", "Low:"))
        self.critical_v_label.setText(_translate("MainWindow", "Critical:"))
        self.voltage_label.setText(_translate("MainWindow", "Actual voltage:"))

import resources_rc
