# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 841, 691))
        self.widget.setStyleSheet("#widget{\n"
"background-image: url(:/Robot_Background.jpg);\n"
"}")
        self.widget.setObjectName("widget")
        self.m_05_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_05_spinbox.setGeometry(QtCore.QRect(60, 60, 71, 30))
        self.m_05_spinbox.setMaximum(300.0)
        self.m_05_spinbox.setSingleStep(0.293)
        self.m_05_spinbox.setObjectName("m_05_spinbox")
        self.m_03_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_03_spinbox.setGeometry(QtCore.QRect(170, 60, 71, 30))
        self.m_03_spinbox.setMaximum(300.0)
        self.m_03_spinbox.setSingleStep(0.293)
        self.m_03_spinbox.setObjectName("m_03_spinbox")
        self.m_01_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_01_spinbox.setGeometry(QtCore.QRect(280, 60, 71, 30))
        self.m_01_spinbox.setMaximum(300.0)
        self.m_01_spinbox.setSingleStep(0.293)
        self.m_01_spinbox.setObjectName("m_01_spinbox")
        self.m_02_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_02_spinbox.setGeometry(QtCore.QRect(490, 60, 71, 30))
        self.m_02_spinbox.setMaximum(300.0)
        self.m_02_spinbox.setSingleStep(0.293)
        self.m_02_spinbox.setObjectName("m_02_spinbox")
        self.m_04_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_04_spinbox.setGeometry(QtCore.QRect(590, 60, 71, 30))
        self.m_04_spinbox.setMaximum(300.0)
        self.m_04_spinbox.setSingleStep(0.293)
        self.m_04_spinbox.setObjectName("m_04_spinbox")
        self.m_06_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_06_spinbox.setGeometry(QtCore.QRect(700, 60, 71, 30))
        self.m_06_spinbox.setMaximum(300.0)
        self.m_06_spinbox.setSingleStep(0.293)
        self.m_06_spinbox.setObjectName("m_06_spinbox")
        self.m_07_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_07_spinbox.setGeometry(QtCore.QRect(220, 230, 71, 30))
        self.m_07_spinbox.setMaximum(300.0)
        self.m_07_spinbox.setSingleStep(0.293)
        self.m_07_spinbox.setObjectName("m_07_spinbox")
        self.m_08_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_08_spinbox.setGeometry(QtCore.QRect(550, 230, 71, 30))
        self.m_08_spinbox.setMaximum(300.0)
        self.m_08_spinbox.setSingleStep(0.293)
        self.m_08_spinbox.setObjectName("m_08_spinbox")
        self.m_09_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_09_spinbox.setGeometry(QtCore.QRect(150, 360, 71, 30))
        self.m_09_spinbox.setMaximum(300.0)
        self.m_09_spinbox.setSingleStep(0.293)
        self.m_09_spinbox.setObjectName("m_09_spinbox")
        self.m_10_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_10_spinbox.setGeometry(QtCore.QRect(610, 350, 71, 30))
        self.m_10_spinbox.setMaximum(300.0)
        self.m_10_spinbox.setSingleStep(0.293)
        self.m_10_spinbox.setObjectName("m_10_spinbox")
        self.m_11_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_11_spinbox.setGeometry(QtCore.QRect(180, 290, 71, 30))
        self.m_11_spinbox.setMaximum(300.0)
        self.m_11_spinbox.setSingleStep(0.293)
        self.m_11_spinbox.setObjectName("m_11_spinbox")
        self.m_12_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_12_spinbox.setGeometry(QtCore.QRect(590, 290, 71, 30))
        self.m_12_spinbox.setMaximum(300.0)
        self.m_12_spinbox.setSingleStep(0.293)
        self.m_12_spinbox.setObjectName("m_12_spinbox")
        self.m_13_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_13_spinbox.setGeometry(QtCore.QRect(190, 430, 71, 30))
        self.m_13_spinbox.setMaximum(300.0)
        self.m_13_spinbox.setSingleStep(0.293)
        self.m_13_spinbox.setObjectName("m_13_spinbox")
        self.m_14_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_14_spinbox.setGeometry(QtCore.QRect(580, 430, 71, 30))
        self.m_14_spinbox.setMaximum(300.0)
        self.m_14_spinbox.setSingleStep(0.293)
        self.m_14_spinbox.setObjectName("m_14_spinbox")
        self.m_15_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_15_spinbox.setGeometry(QtCore.QRect(180, 510, 71, 30))
        self.m_15_spinbox.setMaximum(300.0)
        self.m_15_spinbox.setSingleStep(0.293)
        self.m_15_spinbox.setObjectName("m_15_spinbox")
        self.m_16_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_16_spinbox.setGeometry(QtCore.QRect(580, 510, 71, 30))
        self.m_16_spinbox.setMaximum(300.0)
        self.m_16_spinbox.setSingleStep(0.293)
        self.m_16_spinbox.setObjectName("m_16_spinbox")
        self.m_17_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_17_spinbox.setGeometry(QtCore.QRect(130, 580, 71, 30))
        self.m_17_spinbox.setMaximum(300.0)
        self.m_17_spinbox.setSingleStep(0.293)
        self.m_17_spinbox.setObjectName("m_17_spinbox")
        self.m_18_spinbox = QtWidgets.QDoubleSpinBox(self.widget)
        self.m_18_spinbox.setGeometry(QtCore.QRect(640, 580, 71, 30))
        self.m_18_spinbox.setMaximum(300.0)
        self.m_18_spinbox.setSingleStep(0.293)
        self.m_18_spinbox.setObjectName("m_18_spinbox")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(850, 0, 220, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 180))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(100, 0, 90, 28))
        self.comboBox.setBaseSize(QtCore.QSize(90, 0))
        self.comboBox.setAutoFillBackground(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(18)
        self.comboBox.setMaxCount(18)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 66, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 66, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 66, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 81, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 150, 91, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 110, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(0, 190, 91, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 41, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 41, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 170, 41, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 41, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 250, 41, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 230, 41, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 90, 41, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 50, 41, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(0, 30, 91, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(20, 70, 41, 20))
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 260))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 71, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(30, 150, 71, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(30, 170, 71, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(30, 190, 71, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(30, 210, 71, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.label_30.setObjectName("label_30")
        self.voltage = QtWidgets.QLabel(self.groupBox_3)
        self.voltage.setGeometry(QtCore.QRect(120, 230, 66, 20))
        self.voltage.setText("")
        self.voltage.setObjectName("voltage")
        self.verticalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Stato motore "))
        self.label.setText(_translate("MainWindow", "Torque"))
        self.label_2.setText(_translate("MainWindow", "Goal Position"))
        self.label_3.setText(_translate("MainWindow", "Position"))
        self.label_4.setText(_translate("MainWindow", "Speed"))
        self.label_5.setText(_translate("MainWindow", "Goal Speed"))
        self.label_6.setText(_translate("MainWindow", "Moving"))
        self.label_7.setText(_translate("MainWindow", "Temperature"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dati IMU"))
        self.label_8.setText(_translate("MainWindow", "Speed"))
        self.label_9.setText(_translate("MainWindow", "Acceleration"))
        self.label_10.setText(_translate("MainWindow", "X:"))
        self.label_11.setText(_translate("MainWindow", "Y:"))
        self.label_12.setText(_translate("MainWindow", "Z:"))
        self.label_13.setText(_translate("MainWindow", "X:"))
        self.label_14.setText(_translate("MainWindow", "Z:"))
        self.label_15.setText(_translate("MainWindow", "Y:"))
        self.label_16.setText(_translate("MainWindow", "Z:"))
        self.label_17.setText(_translate("MainWindow", "X:"))
        self.label_18.setText(_translate("MainWindow", "Speed"))
        self.label_19.setText(_translate("MainWindow", "Y:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Stato batteria"))
        self.label_20.setText(_translate("MainWindow", "FW ver:"))
        self.label_21.setText(_translate("MainWindow", "Active:"))
        self.label_22.setText(_translate("MainWindow", "Profile:"))
        self.label_23.setText(_translate("MainWindow", "Good:"))
        self.label_24.setText(_translate("MainWindow", "Src type:"))
        self.label_25.setText(_translate("MainWindow", "Levels:"))
        self.label_26.setText(_translate("MainWindow", "Max:"))
        self.label_27.setText(_translate("MainWindow", "Good:"))
        self.label_28.setText(_translate("MainWindow", "Low:"))
        self.label_29.setText(_translate("MainWindow", "Critical:"))
        self.label_30.setText(_translate("MainWindow", "Actual voltage:"))

import resources_rc
